#! /bin/sh
#
# chkconfig: - 55 45
# description:	The ssEngine daemon is a madhouse ad service.
# processname: ssEngine
# pidfile: /services/ssEngine/run/ssengine.pid

# Standard LSB functions
#. /lib/lsb/init-functions

# Source function library.
. /etc/init.d/functions

CONFFILE="/services/ssEngine/conf/ssengine.conf"
OPTIONS=""

# Check that networking is up.
. /etc/sysconfig/network

if [ "$NETWORKING" = "no" ]
then
	exit 0
fi

RETVAL=0
prog="ssEngine"
pidfile=${PIDFILE-/services/ssEngine/run/ssengine.pid}
lockfile=${LOCKFILE-/var/lock/subsys/ssengine}

start () {
	echo -n $"Starting $prog: "

	daemon --pidfile ${pidfile} /services/ssEngine/ssEngine -m daemon -c $CONFFILE $OPTIONS
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && touch ${lockfile}
}
stop () {
	echo -n $"Stopping $prog: "
	killproc -p ${pidfile} /services/ssEngine/ssEngine
	RETVAL=$?
	echo
	if [ $RETVAL -eq 0 ] ; then
		rm -f ${lockfile} ${pidfile}
	fi
}

restart () {
        stop
        start
}


# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  status)
	status -p ${pidfile} memcached
	RETVAL=$?
	;;
  restart|reload|force-reload)
	restart
	;;
  condrestart|try-restart)
	[ -f ${lockfile} ] && restart || :
	;;
  *)
	echo $"Usage: $0 {start|stop|status|restart|reload|force-reload|condrestart|try-restart}"
	RETVAL=2
        ;;
esac

exit $RETVAL
